### ISSUE TITLE
Lemma attribute matches any part of the lemma

### ISSUE THREAD

**Issue by jaumeortola** [apertium/apertium-lex-tools#3]
`<match lemma="ver" tags="vblex.*"/>` matches any verb containing the string "ver": ver, devolver, revolver, verter, versionar, versar... (72 verbs in Spanish).

We strongly need a way to match literally a lemma: "ver" and only "ver". 

Secondarily, it would be nice (but not so important) to be able to match parts of words (or more generally any regular expression). For example: any word ending in "encia".

**Comment by jaumeortola** [comment]
I continue to find bugs in the LRX (lexical selection file). 

This one in the spa-cat.lrx file causes the process to freeze:

`<rule weight="1"><or><match tags="det.*"/><match tags="adj.*"/><match tags="n.*"/><match tags="vblex.pp.*"/></or><match lemma="Estados Unidos"><select lemma="Estats Units"/></match>
</rule>`

This one matches adverbs, although adverbs are not in the rule: 
`<rule weight="1"><or><match tags="det.*"/><match tags="adj.*"/><match tags="vblex.pp.*"/><match tags="n.*"/></or><match lemma="Estados Unidos"><select lemma="Estats Units"/></match></rule>`

I am very interested in fixing these issues because I am using this module a lot.

**Comment by ftyers** [comment]
Can you give the example input too ?

**Comment by jaumeortola** [comment]
Input Spanish sentence: `Actualmente Estados Unidos.`

By the way, if these rules are used in an empyt LRX file, there is no problem. So there is some undesired interaction between rules.
`<rules>
  <rule weight="0.5">
    <match lemma="Estados Unidos">
      <select lemma="els Estats Units"/>
    </match>
  </rule>
  <rule weight="1">
    <or>
      <match tags="det.*"/>
      <match tags="adj.*"/>
      <match tags="vblex.pp.*"/>
      <match tags="n.*"/>
    </or>
    <match lemma="Estados Unidos">
      <select lemma="Estats Units"/>
    </match>
  </rule>
</rules>`

However, the first reported bug (about "ver") doesn't disappear in an empty file.

**Comment by hectoralos** [comment]
I have exactly the same bug in cat-por and por-cat. For example, in the first one, the relevant rules are:
```
<!-- com > como, quanto -->
  <rule weight="0.6">
     <match lemma="com" tags="adv"><select lemma="como"/></match>
  </rule>
  <rule weight="1.0">
     <match lemma="tant"/>
     <match lemma="com" tags="adv"><select lemma="quanto"/></match>
  </rule>
```
It works for "tan gran com" :
```
echo "tan gran com" | apertium -d . cat-por-lex
1:SELECT:0.60000:com<adv>:como<adv>
^tan<adv>/tão<adv>$ ^gran<adj><mf><sg>/grande<adj><mf><sg>$ ^com<adv>/como<adv>$^.<sent>/.<sent>$
```
But it does not work for "tan important com" (the second rule is chosen by mistake):
```
echo "tan important com" | apertium -d . cat-por-lex
1:SELECT:1.00000:com<adv>:quanto<adv>
^tan<adv>/tão<adv>$ ^important<adj><mf><sg>/importante<adj><mf><sg>$ ^com<adv>/quanto<adv>$^.<sent>/.<sent>$
```

In the por-cat side, an example is:
```
  <rule weight="1.0">
     <or>
       <match lemma="traduzir" tags="vblex.*"/>
       <match lemma="viajar" tags="vblex.*"/>
       <!--       <match lemma="ir" tags="vblex.*"/> -->
     </or>
     <match lemma="para" tags="pr"><select lemma="a"/></match>
  </rule>
```
If I uncomment the match with lemma="ir", then "para" is translated as "a" for all verbs ending in "ir".

**Comment by jaumeortola** [comment]
Hi @ftyers,

With the current nightly version, this bug seems to be fixed. Does it make sense to you?

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/lttoolbox/commit/a0fa2b453c055ea6c077a750cfdb696e2b68a01f may have affected it?

**Comment by unhammer** [comment]
The issue reported by https://github.com/apertium/apertium-lex-tools/issues/3#issue-325618153 seems similar to what was fixed in 5d06817543882cdbf17fbbf16d7c99ae3ebd29ce where rules looking for `lemma="en"` would match input lemma "den". @hectoralos  is the

> `<match lemma="ver" tags="vblex.*"/>` matches any verb containing the string "ver": ver, devolver, revolver, verter, versionar, versar... (72 verbs in Spanish).

problem solved?

The issues in https://github.com/apertium/apertium-lex-tools/issues/3#issuecomment-422532774 are two separate bugs that should've had their own issues @jaumeortola are those both solved as well? (The issue about matching a rule that shouldn't seems like #1 / #12 )

**Comment by jaumeortola** [comment]
All the bugs reported by me here are fixed: the wrong matching, the freezing. The bug reported by @hectoralos seems also fixed. I tested "tan important com" in cat>por and the result is: 
```
echo "tan important com" | apertium -d . cat-por-lex
1:SELECT:0.60000:com<adv>:como<adv>
^tan<adv>/tão<adv>$ ^important<adj><mf><sg>/importante<adj><mf><sg>$ ^com<adv>/como<adv>$^.<sent>/.<sent>$
```
Will this behavior be stable from now on? If yes, the issue can be closed, and we will adjust the rules accordingly.

**Comment by unhammer** [comment]
Seems we can close this then. Whether it will be stable, well, many language pairs are dependent on the fixed behaviour and will hopefully notice regressions, but I'll look into adding some tests too :)

**Comment by unhammer** [comment]
Actually, the original issue is not solved. When the rule says to lemma "ver":

https://github.com/apertium/apertium-lex-tools/blob/master/testing/issue3-prefix.xml#L3

and the input is "aver", which shouldn't match:

https://github.com/apertium/apertium-lex-tools/blob/master/testing/issue3-prefix.input#L1

the rule still matches and we get

```
^aver<vblex>/aver<vblex>$ ^X<adv>/X<adv>$
```

instead of

```
^aver<vblex>/aver<vblex>$ ^X<adv>/X<adv>/Y<adv>$
```

**Comment by jaumeortola** [comment]
In my current installation (spa-cat) it is working fine. I cannot reproduce the issue.

**Comment by unhammer** [comment]
Nevermind, tests weren't using -m :(
